### PR TITLE
Made Close command for Creator only

### PR DESCRIPTION
**Pull request by Arisamiga**
Closes https://github.com/kiwec/osu-ranked-lobbies/issues/72

### CODE REVIEW

**Comment by kiwec** [comment]
better to close the lobby instantly

**Comment by Arisamiga** [comment]
> better to close the lobby instantly

Sounds Good!

**Comment by kiwec** [comment]
no need for "Lobby Is closing" message either since it closes instantly

**Comment by kiwec** [comment]
now edit the command list in faq so it says !close instead of !mp close

**Pull request merged**
