### PR TITLE
Made Buttons and Profile Pictures more Friendly for Mobile

### PR DESCRIPTION
**Pull request by Arisamiga**
Made it so the buttons and Profile pictures don't get squished by small resolutions!

### CODE REVIEW

**Comment by kiwec** [comment]
Should use the TailwindCSS classes directly instead of adding more CSS.

**Comment by Arisamiga** [comment]
> Should use the TailwindCSS classes directly instead of adding more CSS.

Alright! I used the `max-sm`

**Comment by kiwec** [comment]
Doesn't do anything?

2023-02-28-202910_326x139_scrot

**Comment by Arisamiga** [comment]
> Doesn't do anything?
> 
> 2023-02-28-202910_326x139_scrot

This works when I try it. 🤔  


What is basically meant to do is to bring the right buttons down to create more space at the top
image

**Comment by kiwec** [comment]
in prod because i was too lazy to checkout master
as you can see it doesn't work lol whatever

**Pull request merged**
